# Configuration file for the STM32 for VSCode extension
# Arrays can be inputted in two ways. One is: [entry_1, entry_2, ..., entry_final]
# or by adding an indented list below the variable name e.g.:
# VARIABLE:
# - entry_1
# - entry_2

# The project name
target: fenice-bms
# Can be C or C++
language: C

optimization: Og

# MCU settings
targetMCU: stm32f4x
cpu: -mcpu=cortex-m4
fpu: -mfpu=fpv4-sp-d16
floatAbi: -mfloat-abi=hard
# ldscript: STM32F446RETx_FLASH.ld # linker script
ldscript: STM32F446RETx_FLASH_shifted.ld # linker script

# Compiler definitions. The -D prefix for the compiler will be automatically added.
cDefinitions: 
  - USE_HAL_DRIVER
  - STM32F446xx
  - primary_NETWORK_IMPLEMENTATION
  - bms_NETWORK_IMPLEMENTATION
  - primary_WATCHDOG_IMPLEMENTATION 
  - bms_WATCHDOG_IMPLEMENTATION 
  - WATCHDOG_IGNORE
  - TEMP_ERROR_ENABLE
  - TEMP_GROUP_ERROR_ENABLE

cxxDefinitions: []
asDefinitions: []

# Compiler flags
cFlags: []
cxxFlags: []
assemblyFlags: 
  - -specs=nosys.specs
linkerFlags:
  - -u_printf_float


# libraries to be included. The -l prefix to the library will be automatically added.
# Mind that non standard libraries should have a path to their respective directory.
libraries: 
  - c
  - m
  - nosys

libraryDirectories: []

# Files or folders that will be excluded from compilation.
# Glob patterns (https://www.wikiwand.com/en/Glob_(programming)) can be used.
# Do mind that double stars are reserved in yaml
# these should be escaped with a: \ or the name should be in double quotes e.g. "**.test.**"
excludes: 
  - "**/[Ee]xamples/**"
  - "**/[Ee]xample/**"
  - "**/*[Tt]est*/**"
  - "**/*[Tt]est*"


# Include directories (directories containing .h or .hpp files)
# If a CubeMX makefile is present it will automatically include the include directories from that makefile.
includeDirectories: 
  - Inc/**
  - lib/can/lib/bms/**
  - lib/can/lib/primary/**
  - lib/micro-libs/blinky/inc/**
  - lib/micro-libs/cli-legacy/**
  - lib/micro-libs/eeprom-config/**
  - lib/micro-libs/m95256/**
  - lib/micro-libs/min-heap/inc/**
  - lib/micro-libs/ring-buffer/inc/**
  - lib/micro-libs/timer-utils/**
  - lib/micro-libs/pwm/**
  - lib/llist/**


# Files that should be included in the compilation.
# If a CubeMX makefile is present it will automatically include the  c and cpp/cxx files from that makefile.
# Glob patterns (https://www.wikiwand.com/en/Glob_(programming)) can be used.
# Do mind that double stars are reserved in yaml
# these should be escaped with a: \ or the name should be in double quotes e.g. "HARDWARE_DRIVER*.c"
sourceFiles:  
  - Src/**
  - lib/can/lib/bms/bms_network.c
  - lib/can/lib/bms/bms_watchdog.c
  - lib/can/lib/primary/primary_network.c
  - lib/can/lib/primary/primary_watchdog.c
  - lib/micro-libs/blinky/src/**
  - lib/micro-libs/cli-legacy/**
  - lib/micro-libs/eeprom-config/**
  - lib/micro-libs/m95256/**
  - lib/micro-libs/min-heap/src/**
  - lib/micro-libs/ring-buffer/src/**
  - lib/micro-libs/timer-utils/**
  - lib/micro-libs/pwm/**
  - lib/llist/**



# When no makefile is present it will show a warning pop-up.
# However when compilation without the CubeMX Makefile is desired, this can be turned of.
suppressMakefileWarning: false
    
